version: '1'

services:
  web:
    image: nginx:latest
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/main.conf:/etc/nginx/sites-available/example.conf
