---
- hosts: localhost
  tasks:

    # Install and settings for nginx
    - name: Installs ngnix web server
      apt: name=nginx state=latest

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: removing default settnig and folder for nginx
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/www/*
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default
        - /etc/nginx/nginx.conf

    - name: creates directory
      file:
        path: /var/www/{{ inventory_hostname }}
        state: directory

    - name: copy the site config file
      template:
        src: /root/ansible/templates/static_site.j2
        dest: /etc/nginx/sites-available/{{ inventory_hostname }}.conf

    - name: copy the nginx config file
      copy:
        src: /root/ansible/config/nginx.conf
        dest: /etc/nginx/

    - name: create symlink
      file:
        src=/etc/nginx/sites-available/{{ inventory_hostname }}.conf
        dest=/etc/nginx/sites-enabled
        state=link

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    # Install and settings for letsencrypt
    - block:
        - name: install python-dev
          apt: name=python-dev state=latest

        - name: copy the python config file
          copy:
            src: /root/ansible/config/acme-tiny.py
            dest: /usr/local/bin/
            mode: a+x

        - name: copy the ssl config
          copy:
            src: /root/ansible/template/issue-certificate.sh.j2
            dest: /usr/local/bin/
            mode: a+x
