---
- hosts: localhost
  tasks:

    # Install and settings for nginx
    - name: Installs ngnix web server
      apt:
        name: nginx
        state: latest

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: removing default settnig and folder for nginx
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/www/*
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default
        - /etc/nginx/nginx.conf

    - name: creates directory for suite
      file:
        path: /var/www/{{ host_name }}
        owner: www-data
        group: www-data
        state: directory

    - name: copy the site config file
      template:
        src: ./templates/static_site.j2
        dest: /etc/nginx/sites-available/{{ host_name }}.conf
      notify:
        - restart nginx

    - name: copy the nginx config file
      copy:
        src: ./config/nginx.conf
        dest: /etc/nginx/
      notify:
        - restart nginx

    - name: create symlink
      file:
        path: /etc/nginx/sites-available/{{ host_name }}.conf
        src: /etc/nginx/sites-enabled
        state: link
        force: yes
      notify:
        - restart nginx

    # Install and settings for letsencrypt
    - block:
      - name: install python-dev
        apt:
          name: python-dev
          state: latest

      - name: copy the python config file
        copy:
          src: ./config/acme-tiny.py
          dest: /usr/local/bin/
          mode: a+x

      - name: copy the ssl config
        template:
          src: ./templates/issue-certificate.sh.j2
          dest: /usr/local/bin/
          mode: a+x

      - name: create the Let's Encrypt / ACME challenge path
        file:
          path: /var/www/letsencrypt/.well-known/acme-challenge
          state: directory

      - name: run a script
        script: /usr/local/bin/issue-certificate.sh

      - name: restart nginx
        service:
          name: nginx
          state: restarted
